"""Emit the browser assets the course site's live labs read, from the shipped SQL + semantic files.

Keeps one source of truth. The SQL you run locally is byte-for-byte the SQL the page runs in
your browser, and the golden questions the eval scores are the golden questions the b9 lab
scores. Run this after editing anything in sql/ or semantic/.

    assets/bazaar-star.js   window.BAZAAR_STAR_SQL   (sql/10 + 11 + 12 + 20 + 40)
    assets/bazaar-golden.js window.BAZAAR_GOLDEN     (semantic/golden_questions.jsonl)

The OLTP source seed (assets/bazaar-seed.js) is emitted by gen_bazaar_data.py instead, since
it carries the generated data.

Usage:
    python python/build_browser_assets.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SQL = ROOT / "sql"
ASSETS = ROOT / "assets"
GOLDEN = ROOT / "semantic" / "golden_questions.jsonl"

STAR_FILES = [
    "10_dim_ddl.sql",
    "11_fact_ddl.sql",
    "12_oltp_to_star.sql",
    "20_marts.sql",
    "40_agent_views.sql",
]


def js_template_literal(text: str) -> str:
    return text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def build_star() -> None:
    parts = []
    for filename in STAR_FILES:
        parts.append(f"-- ===== {filename} =====")
        parts.append((SQL / filename).read_text().strip())
        parts.append("")
    body = js_template_literal("\n".join(parts))
    js = (
        "/* bazaar-star.js - dimensions, facts, marts and agent views, built FROM the OLTP\n"
        "   source in bazaar-seed.js exactly as a real load would. Generated by\n"
        "   python/build_browser_assets.py from sql/10, 11, 12, 20 and 40 - the same files you\n"
        "   run locally, so the numbers on the page and the numbers on your laptop match.\n"
        "   Bump ?v= on change (Pages caches hard). */\n\n"
        "window.BAZAAR_STAR_SQL = `\n" + body + "`;\n"
    )
    (ASSETS / "bazaar-star.js").write_text(js)
    print(f"  assets/bazaar-star.js      {len(js):>8,} bytes  ({len(STAR_FILES)} sql files)")


def build_golden() -> None:
    entries = [json.loads(line) for line in GOLDEN.read_text().splitlines() if line.strip()]
    js = (
        "/* bazaar-golden.js - the 20-question golden set the b9 lab scores. Generated by\n"
        "   python/build_browser_assets.py from semantic/golden_questions.jsonl, so the browser\n"
        "   scorecard and python/eval_golden_questions.py grade the same questions with the\n"
        "   same SQL. Each entry carries the grounded query, the query an ungrounded model\n"
        "   actually writes, and what goes wrong in it. */\n\n"
        "window.BAZAAR_GOLDEN = " + json.dumps(entries, indent=2) + ";\n"
    )
    (ASSETS / "bazaar-golden.js").write_text(js)
    print(f"  assets/bazaar-golden.js    {len(js):>8,} bytes  ({len(entries)} questions)")


def main() -> None:
    ASSETS.mkdir(exist_ok=True)
    print("Building browser assets from sql/ and semantic/")
    build_star()
    build_golden()
    print("Remember to bump the ?v= query string on the pages that load them.")


if __name__ == "__main__":
    main()
